config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:ner, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'delete'
  
  root to: "sessions#new"
  
  resources :microposts
  resources :users

  get "users/:id/contents", :controller => 'users', :action => 'contents'
  get "top", :controller => 'top', :action => 'index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :length => { :minimum => 8, :maximum => 12}
	validates :password, :length => {:minimum => 4}
	has_many :microposts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize

  def authorize ##ユーザ認証コード
  	if session[:login] != true
  		redirect_to signin_path
  	end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  require 'rubygems'
  require 'twitter'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.eager_load(:user)
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
    @users = User.all
    @users_selected = User.first.id
  end

  # GET /microposts/1/edit
  def edit
    @users = User.all
    @users_selected = @micropost.user_id
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        twit("新規：" + @micropost.content)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        twit("編集："+@micropost.content)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    twit("削除："+@micropost.content)
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end

    def twit(tweet) ## Twitterへのツイート
      client = Twitter::REST::Client.new do |config|
        config.consumer_key = "f4oh7MxGyT0wF5oJQlDYSrDQZ"
        config.consumer_secret = "CoiAo3iRKS2t7Zwru3skFBANopZZiCUVHi3xqWAxDvSC6ggROp"
        config.access_token = "727104969376059394-3MMr5SHvl2JwiiSPs5vIxHKfAkoGL6T"
        config.access_token_secret = "LIz0yTC4MbBUrjAqr54RzosIOoRSa6GxCpbNXmESVRuDI"
      end
      begin
        tweet = (tweet.length > 140) ? tweet[0..139].to_s : tweet
        client.update(tweet.chomp)
      rescue => e
        #ツイートエラー処理
        Rails.logger.error "<<twitter.rake::tweet.update ERROR : #{e.message}>>"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize

	def create

		if params[:session][:username].blank? || params[:session][:password].blank?
			redirect_to signin_path, alert: "ユーザ名またはパスワードを入力してください。"
			session[:login] = false
			return
		end

		@username = User.where("name = \'" + params[:session][:username] + "\'")

		if @username.nil? || @username.size != 1
			redirect_to signin_path, alert: "ユーザが存在しません。"
			session[:login] = false
			return
		end

		@password = User.where("name = \'" + params[:session][:username] + "\' and password = \'" + params[:session][:password] + "\'")
		puts @password.size

		if @password.size == 1
			session[:login] = true
			redirect_to "/top"
		else
			session[:login] = false
			redirect_to signin_path, alert: "パスワードが間違っています。"
		end
	end

	def new
		if session[:login] == true
			redirect_to "/top"
		end
	end

	def destroy
		session[:login] = false
		redirect_to signin_path, alert: "ログアウトしました。"
	end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  # GET /top
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  #GET /addr
  def addr
    @users = User.all
  end

  def addr_show
    @user = User.find(params[:id])
  end

  # GET /users/1/contents
  def contents
    @user = User.find(params[:id])
    @microposts = Micropost.where("user_id = " + params[:id])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @mode = "new"
  end

  # GET /users/1/edit
  def edit
    @mode = "edit"
  end

  # POST /users
  # POST /users.json
  def create
    @mode = params[:user][:bef_mode]
    puts params[:user][:bef_mode]
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # @check_password = User.where("id = " + params[:id] + " and password = \"" + params[:user][:now_password] + "\"")
    # if @check_password.nil? || @check_password.size != 1
    #   redirect_to "/users/" + params[:id], error: "パスワードが間違っています。"
    #   return
    # end
    @mode = params[:user][:bef_mode]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if params[:user][:bef_mode] == "edit" && params[:user][:password].nil?
        params.require(:user).permit(:name, :email, :tel, :comment)
      else
        params.require(:user).permit(:name, :email, :tel, :comment, :password)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'common', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:login] == true %>
<div style="text-align: right;">
  <%= link_to 'ログアウト', '/signout', :method => :delete %>
</div>
<hr>
<% end %>

<%= yield %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= javascript_include_tag 'edit_micropost', 'data-turbolinks-track' => true %>

<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= select :names, :id, @users.map{|t| [t.name, t.id]}, :selected => @users_selected %>
    <%= f.text_field :user_id, :style => "display:none" %>
  </div>
  <div class="actions">
    <%= f.submit :id => "micropost_edit_submit" %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Id</th>
      <th>UserName</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= micropost.user.nil? ? '' : micropost.user.name %></td>
        <td>
          <%= link_to 'Show', micropost %>
          <%= link_to 'Edit', edit_micropost_path(micropost) %>
          <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>
<hr>
<%= link_to 'Top', '/' %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user.nil? ? '' : @micropost.user.name %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/top/index.html.erb
<h1>トップページ</h1>


<table>
  <thead>
    <tr>
      <th>リンク先一覧</th>
    </tr>
  </thead>

  <tbody>
  	<tr>
  	  <td><%= link_to 'ユーザ一覧画面', '/users' %></td>
  	</tr>
  	<tr>
  	  <td><%= link_to 'マイクロポスト一覧画面', '/microposts' %></td>
  	</tr>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '名前' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'メールアドレス' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label '電話番号' %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label 'コメント' %><br>
    <%= f.text_area :comment, :rows => '5' %>
  </div>

  <br>

  <% if @mode == "new" %>
  <div class="field">
    <%= f.label 'パスワード' %><br>
    <%= f.password_field :password %>
  </div>
  <% end %>
  <% if @mode == "edit" %>
<!--   <div class="field">
    <%= f.label '現在のパスワード' %><br>
    <%= f.password_field :now_password %>
  </div> -->
  <div class="field">
    <%= f.label '新しいパスワード' %><br>
    <%= f.password_field :password %>
  </div>
  <% end %>

  <%= f.hidden_field :bef_mode, :value => @mode %>

  <br>

  <div class="actions">
    <%= f.submit '登録', :style => 'width:100px', :confirm => 'よろしいですか？' %>
  </div>
<% end %>

app/views/users/contents.html.erb
<h1>コンテンツ一覧</h1>


<b>名前：　</b><%= @user.name %>

<table>
  <thead>
    <tr>
      <th>コンテンツ</th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'ユーザ一覧に戻る', users_path %>
<hr>
<%= link_to 'トップ画面', '/' %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザ一覧</h1>
<p><%= Time.now %></p>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>電話番号</th>
      <th>コメント</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tel %> </td>
        <td><%= simple_format(user.comment) %></td>
        <td>
          <%= link_to '表示', user %>
          <%= link_to '編集', edit_user_path(user) %>
          <%= link_to '削除', user, method: :delete, data: { confirm: 'よろしいですか？' } %>
          <%= link_to 'コンテンツ', "/users/#{user.id}/contents" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規ユーザ登録', new_user_path %>
<hr>
<%= link_to 'トップ画面', '/' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>電話番号:</strong>
  <%= @user.tel %>
</p>

<p>
  <strong>コメント:</strong>
  <%= simple_format(@user.comment) %>
</p>


<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '一覧に戻る', users_path %>